apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "demo_app"
  MYSQL_USER: "app-user"
  MYSQL_PASSWORD: "password"
